USETEXTLINKS = 1
STARTALLOPEN = 0
HIGHLIGHT = 1
HIGHLIGHT_BG = '#808080'
ICONPATH = 'images/'
GLOBALTARGET = 'R'
foldersTree = gFld('', '')
foldersTree.iconSrc = ICONPATH + 'ftv2blank.gif'
foldersTree.treeID = 'Tree1'

docAux = insDoc(foldersTree, gLnk('R', '&nbsp;Welcome&nbsp;', 'Welcome.htm'))
xgetting_started = insFld(foldersTree, gFld('&nbsp;Getting&nbsp;Started&nbsp;', 'getting_started.htm'))
docAux = insDoc(xgetting_started, gLnk('R', '&nbsp;System&nbsp;Requirements&nbsp;', 'System_Requirements.htm'))
docAux = insDoc(xgetting_started, gLnk('R', '&nbsp;Try&nbsp;for&nbsp;Free&nbsp;', 'Installing_from_a_CD.htm'))
xSettings = insFld(foldersTree, gFld('&nbsp;Settings&nbsp;', 'Settings.htm'))
docAux = insDoc(xSettings, gLnk('R', '&nbsp;User&nbsp;Settings&nbsp;', 'Basic_Function_1.htm'))
docAux = insDoc(xSettings, gLnk('R', '&nbsp;Service&nbsp;Rates&nbsp;', 'Service_Rates.htm'))
docAux = insDoc(xSettings, gLnk('R', '&nbsp;Service&nbsp;Groups&nbsp;', 'service_groups.htm'))
docAux = insDoc(xSettings, gLnk('R', '&nbsp;System&nbsp;Setup&nbsp;', 'system_setup.htm'))
docAux = insDoc(xSettings, gLnk('R', '&nbsp;Subscription&nbsp;', 'Subscription.htm'))
xProjects = insFld(foldersTree, gFld('&nbsp;Projects&nbsp;', 'Projects.htm'))
docAux = insDoc(xProjects, gLnk('R', '&nbsp;Creating&nbsp;a&nbsp;New&nbsp;Project&nbsp;', 'Advanced_Function_1.htm'))
docAux = insDoc(xProjects, gLnk('R', '&nbsp;Project&nbsp;Archives&nbsp;', 'Advanced_Function_2.htm'))
docAux = insDoc(xProjects, gLnk('R', '&nbsp;Projects&nbsp;Page&nbsp;', 'projects_page.htm'))
docAux = insDoc(xProjects, gLnk('R', '&nbsp;Project&nbsp;Details&nbsp;', 'project_details.htm'))
docAux = insDoc(xProjects, gLnk('R', '&nbsp;Edit&nbsp;or&nbsp;Delete&nbsp;a&nbsp;Project&nbsp;', 'edit_or_delete_a_project.htm'))
docAux = insDoc(xProjects, gLnk('R', '&nbsp;Worksheet&nbsp;', 'worksheet.htm'))
xscopes1 = insFld(foldersTree, gFld('&nbsp;Scopes&nbsp;', 'scopes1.htm'))
xscopes1.iconSrc = "images/pageicon_folder.gif"
xscopes1.iconSrcClosed = "images/pageicon_folder.gif"
docAux = insDoc(xscopes1, gLnk('R', '&nbsp;Scopes&nbsp;Page&nbsp;', 'scopes_page.htm'))
docAux = insDoc(xscopes1, gLnk('R', '&nbsp;Worksheet&nbsp;Items&nbsp;', 'edit_or_delete_a_scope.htm'))
docAux = insDoc(xscopes1, gLnk('R', '&nbsp;Manage&nbsp;Scope&nbsp;Items&nbsp;', 'manage_scope_items.htm'))
docAux = insDoc(foldersTree, gLnk('R', '&nbsp;Contacts&nbsp;', 'contacts.htm'))
